name: CI Pipeline - Post-it

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # --- JOB BACKEND ---
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Crucial pour SonarCloud afin d'analyser l'historique

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatique
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Ton secret
        run: |
          cd backend
          mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=arold-takam_post_it \
            -Dsonar.organization=arold-takam \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.branch.name=master \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  # --- JOB FRONTEND ---
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install and Test Frontend
        run: |
          cd frontend
          npm ci
          npm run test -- --run
          npm run build
